### ISSUE TITLE
Is there any way to speed up for heavy datasets

### ISSUE THREAD

**Issue by qrzhang** [wmacnair/psupertime#18]
Hi Will,

Thanks for such a great package!

I am working on a dataset with `40k cells x 2K genes` It has been running around 1.5 h now and seems to run forever. I'm wondering whether there is anything I can do to speed it up?

My command is `psuper_obj  = psupertime(exp, metadata$label, sel_genes='all')`

And my machine is running on macOS Catalina, 3.6 GHz 8-Core Intel Core i9. 

Will appreciate any reply!

Thanks.

Qian

**Comment by wmacnair** [comment]
Hey Qian, glad you're finding it useful :)

My first thought is that it's probably difficult to get much improvement in speed for larger datasets, because the machinery underneath is based on `glmnet`, and that's already pretty heavily optimised (e.g. core code written in `FORTRAN`).

That said, I can give a couple of ideas.

Firstly (although my guess is that this isn't the problem), which part of `psupertime` is slow? If it hangs on
``` processing data```
then you could probably improve things by doing some denoising before you call `psupertime`, and then call `psupertime` with `smooth=FALSE`. (`psupertime` has code for smoothing data, but that's not it's main purpose, and there are many better options out there for denoising which you could try out. I should update the vignettes to reflect that...)

So let's assume that smoothing isn't the issue, and that `psupertime` hangs at
```cross-validation training, 5 folds:```
If that's the case, you could try downsampling. You have 40k cells, so I doubt it will make much difference to the results that are reported if you cut down to 10k cells, or even 5k cells. This also gives you some robustness checks: you could split your 40k cells into 4 chunks of 10k cells, run `psupertime` on each of them, and then compare the reported genes. (I guess it could still be frustratingly slow on 10k cells, in which case you might have to do smaller chunks).

(Another speed-up which I should really add to the package, but which you could also very easily hack together yourself, would be to parallelize the for loop in `train_on_folds`.)

Hope this helps - let me know how you get on!

Best
Will

**Comment by wmacnair** [comment]
Hi, closing this because no response, but happy to open again if you have more Qs.
